using System;
using System.Collections.Generic;

namespace Lapbase.LapbaseModels
{
    public partial class TblPatientConsult
    {
        public int ConsultId { get; set; }
        public int OrganizationCode { get; set; }
        public int UserPracticeCode { get; set; }
        public int PatientId { get; set; }
        public string ConsultType { get; set; }
        public DateTime? DateSeen { get; set; }
        public short VisitType { get; set; }
        public bool CoMorbidityVisit { get; set; }
        public int Seenby { get; set; }
        public decimal Height { get; set; }
        public decimal Weight { get; set; }
        public string WaistCircumference { get; set; }
        public string HipCircumference { get; set; }
        public string SagittalDiameter { get; set; }
        public bool ReportSent { get; set; }
        public string ReservoirVolume { get; set; }
        public bool UpdateD { get; set; }
        public short? Months { get; set; }
        public decimal Bmiweight { get; set; }
        public DateTime? DateNextVisit { get; set; }
        public decimal? BloodPressure { get; set; }
        public decimal? Neck { get; set; }
        public decimal? Hip { get; set; }
        public decimal? Waist { get; set; }
        public string ImageName { get; set; }
        public bool Image { get; set; }
        public string ImageLocation { get; set; }
        public DateTime? ImageDate { get; set; }
        public bool Image1 { get; set; }
        public string ImageLocation1 { get; set; }
        public string ImageName1 { get; set; }
        public DateTime? ImageDate1 { get; set; }
        public bool Image2 { get; set; }
        public string ImageLocation2 { get; set; }
        public string ImageName2 { get; set; }
        public DateTime? ImageDate2 { get; set; }
        public bool Video { get; set; }
        public string VideoLocation { get; set; }
        public string VideoName { get; set; }
        public string VideoResult { get; set; }
        public DateTime? VideoDate { get; set; }
        public decimal WeightLastVisit { get; set; }
        public decimal WeeksLastVisit { get; set; }
        public decimal Bmr { get; set; }
        public decimal Impedance { get; set; }
        public decimal FatPerCent { get; set; }
        public decimal FreeFatMass { get; set; }
        public decimal TotalBodyWater { get; set; }
        public decimal FirstVisitWeight { get; set; }
        public int SystolicBp { get; set; }
        public int DiastolicBp { get; set; }
        public string BprxDetails { get; set; }
        public int Triglycerides { get; set; }
        public int TotalCholesterol { get; set; }
        public int Hdlcholesterol { get; set; }
        public int Ldlcholesterol { get; set; }
        public string LipidRxDetails { get; set; }
        public decimal Hba1c { get; set; }
        public decimal FserumInsulin { get; set; }
        public decimal FbloodGlucose { get; set; }
        public string DiabetesRxDetails { get; set; }
        public decimal Hemoglobin { get; set; }
        public decimal Platelets { get; set; }
        public decimal Wcc { get; set; }
        public decimal Iron { get; set; }
        public decimal Ferritin { get; set; }
        public decimal Transferrin { get; set; }
        public decimal Ibc { get; set; }
        public decimal Folate { get; set; }
        public decimal B12 { get; set; }
        public decimal Sodium { get; set; }
        public decimal Potassium { get; set; }
        public decimal Chloride { get; set; }
        public decimal Bicarbonate { get; set; }
        public decimal Urea { get; set; }
        public decimal Creatinine { get; set; }
        public int Homocysteine { get; set; }
        public int Tsh { get; set; }
        public int T4 { get; set; }
        public int T3 { get; set; }
        public decimal Albumin { get; set; }
        public decimal Calcium { get; set; }
        public decimal Phosphate { get; set; }
        public decimal VitD { get; set; }
        public int Bilirubin { get; set; }
        public decimal AlkPhos { get; set; }
        public decimal Alt { get; set; }
        public decimal Ast { get; set; }
        public decimal Ggt { get; set; }
        public int Tprotein { get; set; }
        public string UserField1 { get; set; }
        public string UserField2 { get; set; }
        public string UserField3 { get; set; }
        public string UserField4 { get; set; }
        public string UserField5 { get; set; }
        public string AsthmaLevel { get; set; }
        public string RefluxLevel { get; set; }
        public string SleepLevel { get; set; }
        public string FertilityLevel { get; set; }
        public string IncontinenceLevel { get; set; }
        public string BackLevel { get; set; }
        public string ArthritisLevel { get; set; }
        public string Cvdlevel { get; set; }
        public DateTime? DateCreated { get; set; }
        public string CreatedByUser { get; set; }
        public string CreatedByComputer { get; set; }
        public DateTime? LastModified { get; set; }
        public string ModifiedByUser { get; set; }
        public string ModifiedByComputer { get; set; }
        public string CreatedByWindowsUser { get; set; }
        public string ModifiedByWindowsUser { get; set; }
        public string OtherRxDetails { get; set; }
        public bool? HypertensionProblems { get; set; }
        public bool? LipidRx { get; set; }
        public bool? DiabetesRx { get; set; }
        public bool? BloodPressureRx { get; set; }
        public bool? OtherRx { get; set; }
        public bool? LipidProblems { get; set; }
        public bool? AsthmaProblems { get; set; }
        public bool? SleepProblems { get; set; }
        public bool? IncontinenceProblems { get; set; }
        public bool? BackProblems { get; set; }
        public bool? ArthritisProblems { get; set; }
        public bool? FertilityProblems { get; set; }
        public bool? RefluxProblems { get; set; }
        public bool? DiabetesProblems { get; set; }
        public string UserMemoField1 { get; set; }
        public string UserMemoField2 { get; set; }
        public string Notes2 { get; set; }
        public string Notes { get; set; }
        public DateTime? DateDeleted { get; set; }
        public string DeletedByUser { get; set; }
        public int? PulseRate { get; set; }
        public int? RespiratoryRate { get; set; }
        public int? BloodPressureUpper { get; set; }
        public int? BloodPressureLower { get; set; }
        public string GeneralReview { get; set; }
        public string CardiovascularReview { get; set; }
        public string RespiratoryReview { get; set; }
        public string GastroReview { get; set; }
        public string GenitoReview { get; set; }
        public string ExtremitiesReview { get; set; }
        public string NeurologicalReview { get; set; }
        public int? SatietyStaging { get; set; }
        public string ChiefComplaint { get; set; }
        public string MusculoskeletalReview { get; set; }
        public string SkinReview { get; set; }
        public string PsychiatricReview { get; set; }
        public string EndocrineReview { get; set; }
        public string HematologicReview { get; set; }
        public string Entreview { get; set; }
        public string EyesReview { get; set; }
        public string Pfshreview { get; set; }
        public string MedicationsReview { get; set; }
        public string LapbandAdjustment { get; set; }
        public int? MedicalProvider { get; set; }
        public bool? AdjConsent { get; set; }
        public bool? AdjAntiseptic { get; set; }
        public bool? AdjAnesthesia { get; set; }
        public decimal? AdjAnesthesiaVol { get; set; }
        public bool? AdjNeedle { get; set; }
        public bool? AdjVolume { get; set; }
        public decimal? AdjInitialVol { get; set; }
        public decimal? AdjAddVol { get; set; }
        public decimal? AdjRemoveVol { get; set; }
        public bool? AdjTolerate { get; set; }
        public bool? LetterSent { get; set; }
        public string SupportGroup { get; set; }
        public bool? AdjBarium { get; set; }
        public bool? AdjOmni { get; set; }
        public bool? ProgressReview { get; set; }
        public bool? AdjProtocol { get; set; }
        public bool? RegistryReview { get; set; }
        public string RegistrySleepApnea { get; set; }
        public string RegistryGerd { get; set; }
        public string RegistryHyperlipidemia { get; set; }
        public string RegistryDiabetes { get; set; }
        public string RegistryHypertension { get; set; }
        public bool? RegistryDiabetesDetail { get; set; }
        public bool? RegistryTreatmentDiet { get; set; }
        public bool? RegistryTreatmentOral { get; set; }
        public bool? RegistryTreatmentInsulin { get; set; }
        public bool? RegistryTreatmentOther { get; set; }
        public bool? RegistryTreatmentCombination { get; set; }
        public bool? RegistryReoperation { get; set; }
        public string RegistryReoperationNote { get; set; }
        public bool? RegistrySedetail { get; set; }
        public string RegistrySelist { get; set; }
        public string RegistrySenote { get; set; }
    }
}
