using System;
using System.Collections.Generic;

namespace Lapbase.LapbaseModels
{
    public partial class TblPatientEmrlog
    {
        public int PatientEmrlogId { get; set; }
        public int OrganizationCode { get; set; }
        public int PatientId { get; set; }
        public string DetailsOccupation { get; set; }
        public string DetailsFamilyStructure { get; set; }
        public string DetailsLiveAtHome { get; set; }
        public string DetailsSpouseName { get; set; }
        public string DetailsChildren { get; set; }
        public string DetailsNextOfKinName { get; set; }
        public string DetailsNextOfKinRelation { get; set; }
        public string DetailsNextOfKinAddress { get; set; }
        public string DetailsNextOfKinHomePhone { get; set; }
        public string DetailsNextOfKinWorkPhone { get; set; }
        public string DetailsNextOfKinMobile { get; set; }
        public string DetailsAddContact1Name { get; set; }
        public string DetailsAddContact1Relation { get; set; }
        public string DetailsAddContact1Address { get; set; }
        public string DetailsAddContact1HomePhone { get; set; }
        public string DetailsAddContact1Mobile { get; set; }
        public string DetailsAddContact2Name { get; set; }
        public string DetailsAddContact2Relation { get; set; }
        public string DetailsAddContact2Address { get; set; }
        public string DetailsAddContact2HomePhone { get; set; }
        public string DetailsAddContact2Mobile { get; set; }
        public string BackgroundDiabetes { get; set; }
        public string BackgroundHeartDisease { get; set; }
        public string BackgroundHypertension { get; set; }
        public string BackgroundGout { get; set; }
        public string BackgroundObesity { get; set; }
        public string BackgroundSnoring { get; set; }
        public string BackgroundAsthma { get; set; }
        public string BackgroundHighCholesterol { get; set; }
        public string BackgroundFamilyHistory { get; set; }
        public string BackgroundPastHealth { get; set; }
        public string BackgroundPreviousBariatric { get; set; }
        public string BackgroundPreviousNonBariatric { get; set; }
        public string SpecialInvestigationSuggestedSs { get; set; }
        public string SpecialInvestigationActionSs { get; set; }
        public string SpecialInvestigationSuggestedGe { get; set; }
        public string SpecialInvestigationActionGe { get; set; }
        public string SpecialInvestigationSuggestedSp { get; set; }
        public string SpecialInvestigationActionSp { get; set; }
        public string SpecialInvestigationSuggestedNa { get; set; }
        public string SpecialInvestigationActionNa { get; set; }
        public string SpecialInvestigationSuggestedPs { get; set; }
        public string SpecialInvestigationActionPs { get; set; }
        public string SpecialInvestigationSuggestedOa { get; set; }
        public string SpecialInvestigationActionOa { get; set; }
        public string ReviewSystemPfsh { get; set; }
        public string ReviewSystemGeneral { get; set; }
        public string ReviewSystemGastro { get; set; }
        public string ReviewSystemCardio { get; set; }
        public string ReviewSystemResp { get; set; }
        public string ReviewSystemMusculo { get; set; }
        public string ReviewSystemExtr { get; set; }
        public string ReviewSystemGenito { get; set; }
        public string ReviewSystemSkin { get; set; }
        public string ReviewSystemNeuro { get; set; }
        public string ReviewSystemPsych { get; set; }
        public string ReviewSystemEndo { get; set; }
        public string ReviewSystemHema { get; set; }
        public string ReviewSystemEnt { get; set; }
        public string ReviewSystemEyes { get; set; }
        public string ReviewSystemMeds { get; set; }
        public string Medication { get; set; }
        public bool? AllergyHaveAllergy { get; set; }
        public string AllergyListAllergy { get; set; }
        public bool? AllergyHaveMedication { get; set; }
        public string AllergyListMedication { get; set; }
        public bool? AllergyLatex { get; set; }
        public string AllergyAnesthetic { get; set; }
        public bool? AllergyExcessBleed { get; set; }
        public string AllergyAnestheticRisk { get; set; }
        public string AllergyHaveDrink { get; set; }
        public string AllergyDrinkPerDay { get; set; }
        public string AllergyDrinkPerWeek { get; set; }
        public bool? AllergyDrinkBeer { get; set; }
        public bool? AllergyDrinkWine { get; set; }
        public bool? AllergyDrinkSpirits { get; set; }
        public string AllergySmoke { get; set; }
        public string AllergySmokePerDay { get; set; }
        public bool? AllergyHaveSmoke { get; set; }
        public string AllergyHaveSmokePerDay { get; set; }
        public string AllergyHaveSmokeYears { get; set; }
        public string AllergyHaveSmokeStop { get; set; }
        public string WeightHistoryWeightBirth { get; set; }
        public string WeightHistoryWeightStartSchool { get; set; }
        public string WeightHistoryWeightStartHighSchool { get; set; }
        public string WeightHistoryWeightEndHighSchool { get; set; }
        public string WeightHistoryWeightWork { get; set; }
        public string WeightHistoryWeightMarriage { get; set; }
        public string WeightHistoryLoseYears { get; set; }
        public string WeightHistoryTryMethod { get; set; }
        public string WeightHistoryGroupList { get; set; }
        public string WeightHistoryGroupOther { get; set; }
        public string WeightHistoryPillList { get; set; }
        public string WeightHistoryPillOther { get; set; }
        public string WeightHistoryAdviceList { get; set; }
        public string WeightHistoryAdviceOther { get; set; }
        public string WeightHistoryDietList { get; set; }
        public string WeightHistoryOther { get; set; }
        public string WeightHistoryTreatmentList { get; set; }
        public string WeightHistoryCosmeticList { get; set; }
        public string InvestigationRbs { get; set; }
        public string InvestigationActionRbs { get; set; }
        public string InvestigationAbs { get; set; }
        public string InvestigationActionAbs { get; set; }
        public string InvestigationRft { get; set; }
        public string InvestigationActionRft { get; set; }
        public string InvestigationAbg { get; set; }
        public string InvestigationActionAbg { get; set; }
        public string InvestigationEet { get; set; }
        public string InvestigationActionEet { get; set; }
        public string InvestigationBm { get; set; }
        public string InvestigationActionBm { get; set; }
        public string InvestigationEms { get; set; }
        public string InvestigationActionEms { get; set; }
        public string InvestigationP { get; set; }
        public string InvestigationActionP { get; set; }
        public string InvestigationEkg { get; set; }
        public string InvestigationActionEkg { get; set; }
        public string InvestigationCx { get; set; }
        public string InvestigationActionCx { get; set; }
        public string ExamNotes { get; set; }
        public string ExamGao { get; set; }
        public string ExamHng { get; set; }
        public string ExamHnh { get; set; }
        public string ExamHnm { get; set; }
        public string ExamHnn { get; set; }
        public string ExamCh { get; set; }
        public string ExamCp { get; set; }
        public string ExamAa { get; set; }
        public string ExamLsr { get; set; }
        public string ExamLsb { get; set; }
        public string ExamLsa { get; set; }
        public string ExamMso { get; set; }
        public string ExamMf { get; set; }
        public string ReferralsPa { get; set; }
        public string ReferralsC { get; set; }
        public string ReferralsRp { get; set; }
        public string ReferralsE { get; set; }
        public string ReferralsAp { get; set; }
        public string ReferralsGm { get; set; }
        public string ReferralsO { get; set; }
        public string Complaint { get; set; }
        public string ComplaintNotes { get; set; }
        public string Management { get; set; }
        public bool? AllergyDoDrugs { get; set; }
        public string AllergyDoDrugsNotes { get; set; }
        public string LabNotes { get; set; }
        public string WeightHistoryGainYears { get; set; }
        public decimal? WeightHistoryGainWeight { get; set; }
        public string DetailsMedicareNumber { get; set; }
        public string WeightHistoryGroupDuration { get; set; }
        public string WeightHistoryGroupLose { get; set; }
        public DateTime? DeceasedDate { get; set; }
        public string DetailsPhotoPath { get; set; }
        public string RegistryAntihypertensives { get; set; }
        public string RegistryInsulin { get; set; }
        public string RegistrySleepApnea { get; set; }
        public string RegistryGerd { get; set; }
        public string RegistryHyperlipidemia { get; set; }
        public string RegistryDiabetes { get; set; }
        public string RegistryHypertension { get; set; }
        public int? LogUserPracticeCode { get; set; }
        public DateTime? LogDateTime { get; set; }
        public bool? DetailsDeceasedPrimaryProcedure { get; set; }
        public string DetailsDeceasedNote { get; set; }
    }
}
